-- Creación de Usuario

CREATE USER USR_PARALLEL IDENTIFIED BY P4ssw0rd4567; 

-- Permisos
GRANT EXECUTE ON sys.DBMS_LOCK TO USR_PARALLEL; 
GRANT EXECUTE ON dbms_scheduler TO USR_PARALLEL; 
grant create job to USR_PARALLEL;
GRANT SELECT ON DBA_SCHEDULER_JOBS TO USR_PARALLEL; 
GRANT UNLIMITED TABLESPACE TO USR_PARALLEL; 
